[package]
name = "mazes"
version = "0.1.0"
authors = ["Lakret <rakuretu@gmail.com>"]
edition = "2018"

[lib]
name = "mazes"
path = "src/mod.rs"

[[bin]]
name = "mazes"
path = "src/main.rs"

[dependencies]
svg = "0.8"
