[package]
name = "spreadsheet"
version = "0.1.0"
authors = ["Lakret <Rakuretu@gmail.com>"]
edition = "2021"

[[bin]]
name = "spreadsheets"
path = "src/main.rs"

[dependencies]
graphs = { path =  "../graphs" }
# rand = "0.8"
yew = { version = "0.20.0", features = ["csr"] }
wasm-bindgen = "0.2.83"
